@startuml seq

title Laundry monitoring system: sequence diagram
footer WSN Lab – group 5, SS22

hide footbox
autonumber "<b>[00]</b>"
skinparam shadowing false
skinparam maxMessageSize 120

participant "Gateway" as g
participant "Edge" as e
participant "Sensor" as s
entity "Contiki OS" as c

== Initial discovery ==
e -> e: Announce timeout expired
g <- e: ""EDGE_ANNOUNCE""
g -> g: Add to pool

== Normal operation ==
g -> e: ""Q_STATUS""
g <- c: """sent: status 0""
e -> e: Restart announce timer
e -> s: ""Q_STATUS""
e <- c: ""sent: status 0""
s -> s: Read sensor\nvalues
e <- s: ""A_STATUS""
g <- e: ""A_STATUS""
g -> g: Update UI

== Edge Failure ==
g -> e: ""Q_STATUS""
... no response ...
g <- c: ""sent: status !0""
g -> g: Remove from pool

== Sensor failure ==
g -> e: ""Q_STATUS""
e -> s: ""Q_STATUS""
... no response ...
e <- c: ""sent: status !0""
g <- e: ""UNKNOWN"" status

@enduml
